### ISSUE TITLE
PLUGIN_ROUTE_UP failed with status 1

### ISSUE THREAD

**Issue by war59312** [ValdikSS/openvpn-block-incoming-udp-plugin#1]
Hi,

Thaks a lot for this plugin but I see in the OpenVPN Log:

> Fri Apr 15 19:59:37 2016 PLUGIN_CALL: plugin function PLUGIN_ROUTE_UP failed with status 1: block-incoming-udp-64.dll
> 
> Fri Apr 15 19:59:37 2016 WARNING: route-up plugin call failed

Running openvpn-install-2.3.10-I603 on Windows 8.1 x64.

Normal?

Thanks,

Will

**Comment by ValdikSS** [comment]
Hi,

Please run OpenVPN from the console to see output.

`bin\openvpn.exe config\your-config.ovpn`

**Comment by war59312** [comment]
As, requested:

> Sat Apr 16 13:14:50 2016 OpenVPN 2.3.10 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [PKC
> S11] [IPv6] built on Mar 10 2016
> Sat Apr 16 13:14:50 2016 Windows version 6.2 (Windows 8 or greater)
> Sat Apr 16 13:14:50 2016 library versions: OpenSSL 1.0.1s  1 Mar 2016, LZO 2.09
> Sat Apr 16 13:14:51 2016 UDPv4 link local: [undef]
> Sat Apr 16 13:14:51 2016 UDPv4 link remote: [AF_INET]VPN_IP:VPN_PORT
> Sat Apr 16 13:14:51 2016 WARNING: this configuration may cache passwords in memory --
>  use the auth-nocache option to prevent this
> Sat Apr 16 13:14:51 2016 [Private Internet Access] Peer Connection Initiated with [AF
> _INET]VPN_IP:VPN_PORT
> Sat Apr 16 13:14:53 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
> Sat Apr 16 13:14:53 2016 open_tun, tt->ipv6=0
> Sat Apr 16 13:14:53 2016 TAP-WIN32 device [Local Area Connection] opened: \.\Global\
> {31DA1D0F-754E-4C18-93E4-8B5BBAA36587}.tap
> Sat Apr 16 13:14:53 2016 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.1
> 00.1.6/255.255.255.252 on interface {31DA1D0F-754E-4C18-93E4-8B5BBAA36587} [DHCP-serv
> : 10.100.1.5, lease-time: 31536000]
> Sat Apr 16 13:14:53 2016 Successful ARP Flush on interface [5] {31DA1D0F-754E-4C18-93
> E4-8B5BBAA36587}
> Sat Apr 16 13:14:59 2016 PLUGIN: Starting firewall
> No TAP adapters found!
> Sat Apr 16 13:14:59 2016 PLUGIN: Start failed!
> Sat Apr 16 13:14:59 2016 PLUGIN_CALL: plugin function PLUGIN_ROUTE_UP failed with sta
> tus 1: C:\Users\William.openvpn\bin\block-incoming-udp-64.dll
> Sat Apr 16 13:14:59 2016 WARNING: route-up plugin call failed
> Sat Apr 16 13:14:59 2016 Initialization Sequence Completed
> Sat Apr 16 13:17:59 2016 PLUGIN: Stopping firewall
> Sat Apr 16 13:17:59 2016 PLUGIN: Can't stop firewall!
> Sat Apr 16 13:17:59 2016 PLUGIN_CALL: plugin function PLUGIN_DOWN failed with status
> 1: C:\Users\William.openvpn\bin\block-incoming-udp-64.dll
> Sat Apr 16 13:17:59 2016 ERROR: up/down plugin call failed
> Sat Apr 16 13:17:59 2016 Exiting due to fatal error

The firewall errors and "No TAP adapters found" seems to be BS since it connects just fine and works fine.

Windows firewall and tap adapter are of course enabled and appear to be functioning correctly.

Only happens if I use this plugin. Disable the plugin, remove the line from the config. Then none of these errors are logged.

**Comment by ValdikSS** [comment]
You probably have a custom TAP adapter with different name. Either install standard OpenVPN TAP driver or use PIA client which have this function integrated.

**Comment by war59312** [comment]
Nope, standard TAP Driver.

I simply installed OpenVPN from https://openvpn.net/index.php/open-source/downloads.html

This download link:

https://swupdate.openvpn.org/community/releases/openvpn-install-2.3.10-I603-x86_64.exe

I think it's broken on this build. Will try to confirm.

Edit: Or not, same issue with 2.3.9.

Only thing I can think of is, Windows security updates that just got installed this past Tuesday.

Edit 2: Did a system restore and problem solved. I see what happened. Compared settings from restore points. Indeed a security update disabled IPv6 on the Tap Adapter and caused this problem..

Ouch! What a nasty way of failing though. Should warn user that IPv6 checkbox under Tap Adapter must be selected. Sure that belongs to OpenVPN itself to do.
