### ISSUE TITLE
block-incoming-udp-64.dll location on Windows 10 and the OpenVPN log output

### ISSUE THREAD

**Issue by slrslr** [ValdikSS/openvpn-block-incoming-udp-plugin#3]
Hello, i tried to add the block-incoming-udp-64.dll file into the OpenVPN folders (i think the [README](https://github.com/ValdikSS/openvpn-block-incoming-udp-plugin/blob/master/README.md) does not mention exact folder where the file belong) on my Windows 10 computer.

Then added the suggested line into .ovpn config. file and restarted the VPN connection and in the log file i was searching for the "block-incoming-udp-64" and found following:

> PLUGIN_CALL: POST block-incoming-udp-64.dll/PLUGIN_DOWN status=0
> PLUGIN_CLOSE: block-incoming-udp-64.dll
> WARNING: plugin 'block-incoming-udp-64.dll' specified by a relative pathname -- using an absolute pathname would be more secure
> PLUGIN_INIT: POST block-incoming-udp-64.dll '[block-incoming-udp-64.dll]' intercepted=PLUGIN_DOWN|PLUGIN_ROUTE_UP
> PLUGIN_CALL: POST block-incoming-udp-64.dll/PLUGIN_ROUTE_UP status=0

please does it mean the plugin should work?

**Comment by ValdikSS** [comment]
The plugin was created 4 years ago. In that time, OpenVPN didn't use service model, but just started its process as administrator. I'm not sure if its compatible with service model (it should be, but it hasn't been tested). If you run it without service, you should be able to see some debug text from the plugin on connecting.
You can try to send UDP packets to your PC and check if the plugin blocks the responses.

**Comment by slrslr** [comment]
> If you run it without service

if i know how, i would try it, or:

> send UDP packets to your PC and check if the plugin blocks the responses

i can try this, but i do not know the Linux command, which port to use. My OpenVPN server connection type is UDP if i understand right.

**Comment by ValdikSS** [comment]
>if i know how, i would try it

I believe you can choose between service/no service mode in OpenVPN installer, when you install the software.

**Comment by slrslr** [comment]
And do you know that Linux command to send yours mentioned UDP packet to verify if this plugin works?

**Comment by ValdikSS** [comment]
On the machine with OpenVPN with this plugin running, execute:

`ncat -u -l -p 13318`

On another machine, run:

`nping --udp -p 13318 --data-string 'hello' -c 1 192.0.1.2`

Where `192.0.1.2` is machine #1 IP address. If you see 'hello' in the console on the machine with OpenVPN, it means that the plugin does not work. If you don't see 'hello`, it means that either the plugin is working fine or that you don't have direct connectivity (you're behind router/NAT/firewall/etc).

Both utilities are included in `nmap`, and are available on both Linux and Windows.

**Comment by slrslr** [comment]
Thanks for the guide. I [downloaded nmap](https://nmap.org/download.html) and installed nmap on Windows VPN client machine, reopen administrator command prompt and [executed suggested ncat command](https://nmap.org/book/inst-windows.html#inst-win-exec). Run also other suggested command on another remote machine (different WAN) while in the command i used the public IP of the OpenVPN server and the suggested port and also the port of the openvpn server. None caused "hello" message to appear. I also removed the .ovpn config line "plugin block-incoming-udp-64.dll" and no hello. Maybe i did something wrong or maybe my firewall (router not) already block that traffic. Thank you for help in this thread.

**Comment by ValdikSS** [comment]
You need to send the packet with nping to your real internet IP address, not to the IP address of VPN server. Replace `192.0.1.2` with the IP address of your network connection. The IP address should not be behind NAT/router/firewall.

**Comment by slrslr** [comment]
thanks, so on my VPN client i ran:
ncat -u -l -p 13318

and then i discovered real public IP address of my internet connection (i mean not one of the VPN server, but one returned when not connected to VPN and shown on sites like whatismyip.com)

and pasted that IP into following command:
nping --udp -p 13318 --data-string 'hello' -c 1 ThatIPHere

and ran the command on my VPS that i have in different country.

my VPN client computer not recorded any hello on above mentioned ncat command output..
i then tried to remove the line "plugin block-incoming-udp-64.dll" from ovpn config and tried again. Same result - packet received with reply "Port 13318 unreachable"

We have a router with upnp enabled and a few computers in the network. Router firewall disabled.
Maybe i again failed to understand how this works. Maybe it just means it works good and i am not leaking the data.

**Comment by ValdikSS** [comment]
If you're behind a router, which in 99.9% cases perform NAT, you don't need this plugin. The data may be leaked if you're not behind router (NAT), but for example your PC is directly connected to the ISP link.
